import CartFixedBtn from '@/layouts/CartFixedBtn';
import Footer from '@/layouts/Footer';
import Header from '@/layouts/Header';
import { Open_Sans } from 'next/font/google';
import 'react-modern-drawer/dist/index.css';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import 'slick-carousel/slick/slick-theme.css';
import 'slick-carousel/slick/slick.css';
import './globals.css';
import dynamic from 'next/dynamic';

const ProductDetails = dynamic(() => import('@/components/ProductDetails'));

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const openSans = Open_Sans({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    display: 'swap',
});

export default function RootLayout({ children }) {
    return (
        <html lang="vi">
            <body className={openSans.className}>
                <Header />
                <div className="content pb-14">{children}</div>
                <Footer />
                <CartFixedBtn />
                <ProductDetails />
            </body>
        </html>
    );
}
