import { Open_Sans } from 'next/font/google';
import Header from '@/layouts/Header';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const openSans = Open_Sans({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    display: 'swap',
});

export default function RootLayout({ children }) {
    return (
        <html lang="vi">
            <body className={openSans.className}>
                <Header />
                <div className="content pb-8">{children}</div>
            </body>
        </html>
    );
}
